FROM node:12-alpine AS sg-core-ts

WORKDIR /opt

COPY ./.env /opt/
COPY ./package.json /opt/
RUN npm install

# RUN npm run scripts
# RUN npm run style
# RUN npm run copy-assets

RUN npm install -g nodemon
RUN npm install -g gulp@3.9.1
